/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package STUDENT_RANKING_SYSTEM;

import java.awt.Component;
import javax.swing.JTextField;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;





/**
 *
 * @author User
 */
public class STUDENT_RANKING_SYSTEM extends javax.swing.JFrame {

    /**
     * Creates new form STUDENT_RANKING_SYSTEM
     */
    public STUDENT_RANKING_SYSTEM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        sn = new javax.swing.JTextField();
        rn = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        tm = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        ebiz = new javax.swing.JTextField();
        multimedia = new javax.swing.JTextField();
        java = new javax.swing.JTextField();
        sengeering = new javax.swing.JTextField();
        database = new javax.swing.JTextField();
        english = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        r = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        RANKING = new javax.swing.JButton();
        TRANSCRIPT = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        RESET = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("GRADES"));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jTextField6.setText("jTextField6");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(782, 782, 782)
                .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STUDENT INFORMATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 6, -1, 517));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("STUDENT INFORMATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("MODULES COVERED");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 6, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("REG_NUMBER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("FIRST_NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("SURNAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("TOTAL_MARKS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("RANKING");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("JAVA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("E_BIZ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("MULTIMEDIA");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("DATABASE");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("S_ENGEERING");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("ENGLISH");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("C++");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        sn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(sn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 140, 30));

        rn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(rn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 140, 30));

        fn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, 30));

        tm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(tm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 140, 30));

        a.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 140, 30));

        c.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 100, 30));

        ebiz.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(ebiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 100, 30));

        multimedia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(multimedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 90, 30));

        java.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(java, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 100, 30));

        sengeering.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(sengeering, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 90, 30));

        database.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(database, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 90, 30));

        english.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(english, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 90, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("AVERAGE");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        r.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 140, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "REG_NUMBER", "JAVA", "C++", "E_BIZ", "S_ENGEERING", "MULTIMEDIA", "DATABASE", "ENGLISH", "TOTAL ", "AVERAGE", "RANKING"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 900, 110));

        RANKING.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RANKING.setText("RANKING");
        RANKING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RANKINGActionPerformed(evt);
            }
        });
        getContentPane().add(RANKING, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));

        TRANSCRIPT.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TRANSCRIPT.setText("TRANSCRIPT");
        getContentPane().add(TRANSCRIPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, -1, -1));

        EXIT.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        getContentPane().add(EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, -1, -1));

        RESET.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RESET.setText("RESET");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });
        getContentPane().add(RESET, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, -1, -1));

        DELETE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        DELETE.setText("DELETE");
        getContentPane().add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed
//METHOD TO RESET ALL FIELDS
    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
//reset button to erase every field

 rn.setText(null);
fn.setText(null);
sn.setText(null);
tm.setText(null);
a.setText(null);
a.setText(null);
java.setText(null);
c.setText(null);
ebiz.setText(null);
sengeering.setText(null);
multimedia.setText(null);
database.setText(null);
english.setText(null);
    }//GEN-LAST:event_RESETActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        //EXIT BUTTON TO LEAVE FROM THE CURRENT PAGE
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed
//METHOD TO ENTER AND DISPLAY THE MARKS AND AVERAGE
    private void RANKINGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RANKINGActionPerformed
       //CREATION OF ARRAY OBJECT TO ACCESS THE MARKS FIELDS
       
        double[] obj=new double[14];
        obj[0] =Double.parseDouble(java.getText());
        obj[1] =Double.parseDouble(c.getText());
        obj[2] =Double.parseDouble(ebiz.getText());
        obj[3] =Double.parseDouble(sengeering.getText());
        obj[4] =Double.parseDouble(multimedia.getText());
        obj[5] =Double.parseDouble(database.getText());
        obj[6] =Double.parseDouble(english.getText());
        
        //FORMULA TO ADD UP ALL MARKS OF ONE STUDENT
         obj[7] =obj[0]+obj[1]+obj[2]+obj[3]+obj[4]+obj[5]+obj[6];
         
       //FORMULA TO GET THE AVERAGE OF ONE STUDENT AFTER GETTING THE SUM OR TOTAL
       obj[8] =obj[7]/7;
       
       //OBJECT TO DISPLAY THE TOTAL
       String total=String.format("TOTAL",obj[7]);
       
       //OBJECT TO DISPLAY THE AVERAGE MARKS
       tm.setText(total);
       
       String average=String.format("AVERAGE",obj[8]);
       a.setText(average);
       
       //SET CONDITION TO CONSIDER WHEN RANKING
       
       if(obj[7]>=600)
       {
           r.setText("1ST CLASS");
           
       }
       else if(obj[7]>=500)
       {
           r.setText("2ND UPPER  CLASS");
           
       }
       else if(obj[7]>=400)
       {
           r.setText("2ND LOWER CLASS");
           
       }
       else if(obj[7]>=300)
       {
           r.setText("PASS");
           
       }
       else
           if(obj[7]>=200)
       {
           r.setText("FAIL");
           
       }
       DefaultTableModel table=(DefaultTableModel) 
        
    }//GEN-LAST:event_RANKINGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STUDENT_RANKING_SYSTEM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETE;
    private javax.swing.JButton EXIT;
    private javax.swing.JButton RANKING;
    private javax.swing.JButton RESET;
    private javax.swing.JButton TRANSCRIPT;
    private javax.swing.JTextField a;
    private javax.swing.JTextField c;
    private javax.swing.JTextField database;
    private javax.swing.JTextField ebiz;
    private javax.swing.JTextField english;
    private javax.swing.JTextField fn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField java;
    private javax.swing.JTextField multimedia;
    private javax.swing.JTextField r;
    private javax.swing.JTextField rn;
    private javax.swing.JTextField sengeering;
    private javax.swing.JTextField sn;
    private javax.swing.JTextField tm;
    // End of variables declaration//GEN-END:variables
}
